pub mod authenticators;
pub mod authorization;
pub mod automations;
pub mod budget;
pub mod budget_p05;
pub mod catalog;
pub mod credentials;
pub mod data_governance;
pub mod devices;
pub mod entitlements;
pub mod identity;
pub mod inference;
pub mod machine_identity;
pub mod memberships;
pub mod organizations;
pub mod outbox;
pub mod plugins;
pub mod policy;
pub mod policy_p04;
pub mod policy_p05;
pub mod projects;
pub mod rate_limits;
pub mod rollouts;
pub mod routing;
pub mod runs;
pub mod staff;
pub mod teams;
pub mod tool_policy;
pub mod usage;

#[cfg(test)]
mod p04_domain_tests;
